export const identificationOptions = [
    { code: "CC", description: "Cédula de ciudadanía" },
    { code: "CE", description: "Cédula de extranjería" },
    { code: "NIT", description: "Número de identificación tributario" },
    { code: "TI", description: "Tarjeta de identidad" },
    { code: "PP", description: "Pasaporte" },
    { code: "IDC", description: "Identificador único de cliente" },
    { code: "CEL", description: "Línea del móvil" },
    { code: "RC", description: "Registro civil de nacimiento" },
    { code: "DE", description: "Documento de identificación extranjero" },
    { code: "SE_NIT", description: "Sociedad Extranjera sin Nit" },
    { code: "FIDE", description: "Fideicomiso" },
    { code: "NIT_M", description: "Nit Menores" },
    { code: "RIF_V", description: "RIF Venezuela" },
    { code: "NIT_E", description: "Nit Extranjería" },
    { code: "NIT_N", description: "Nit Persona Natural" },
    { code: "C_DIP", description: "Carnet Diplomático" },
    { code: "RUT", description: "RUT" },
    { code: "CPF", description: "Registro de personas físicas" },
    { code: "CEDULAECU", description: "Cedula Ecuador" },
    { code: "CEDULACOL", description: "Cedula Colombia" },
  ];